### ISSUE TITLE
Error thrown when opening a file

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/livewire#108]
1. Start Livewire.
2. Open a file (ex. readme.adoc in training-repo).
3. Check the console.

 Uncaught TypeError: Cannot read property 'children' of undefined
C:\Git\livewire\node_modules\cheerio\lib\api\traversing.js:10

@MikeTechSpeak was getting a different error about file|open, but it happened at the same operation (opening a file).

The result is that the preview does not work.  Mine is blank, his wouldn't update at all.

I have node version 4.5.0, he has the latest version.

**Comment by ig-ealbert** [comment]
Fixed for me by deleting the node_modules folder and redoing `npm install`.
Mike still gets an error:
C:\Users\mgermann\Documents\GitHub\livewire\app\modules\persistence\index.js:141 TypeError: Cannot read property 'file|opened' of undefined(…)

**Comment by craigshoemaker** [comment]
There is a nested `node_modules` folder in the `app` folder that once deleted allowed @MikeTechSpeak to proceed without an issue.
