### ISSUE TITLE
Getting JavaScript error every time I open Livewire if installed from the server

### ISSUE THREAD

**Issue by luciarodriguez** [Infragistics/livewire#112]
If I don't use the installer and instead pull the latest version through Git, I get the attached error message every time I open the application.

![javascripterror_livewire](https://cloud.githubusercontent.com/assets/14312132/23753482/6c00c15e-04b8-11e7-9c50-ad72a25e552a.png)

**Comment by craigshoemaker** [comment]
@luciarodriguez is this still happening?

**Comment by luciarodriguez** [comment]
Yes, with the version I installed from the server (if I open it up using Git Bash). The installer works fine.

**Comment by luciarodriguez** [comment]
This one's fixed with the latest version from today.

**Comment by craigshoemaker** [comment]
great!
