### ISSUE TITLE
Automatic TFS Checkout

### ISSUE THREAD

**Issue by craigshoemaker** [Infragistics/livewire#12]
Create a hook to TFS that automatically checks out a file upon edit. Most of the work here should be done in a .NET DLL and use Edge.js to sent messages to conduct the work.

**Resources**
- [How can I programmatically check-out an item for edit in TFS?](http://stackoverflow.com/a/9417547/74399)

**Comment by aaguiarz** [comment]
Wouldn't it be possible to use Git for the doc files?

**Comment by craigshoemaker** [comment]
Perhaps. We need to talk to some of the folks who write docs to see if that would propose a problem. Since TFS supports Git it is certainly an option.

**Comment by craigshoemaker** [comment]
Actually the docs will all end up on GitHub anyway, so Git will be assumed :smile: 

Closing this issue.
