### ISSUE TITLE
UX Improvement: Prompt user to install Bower and Gulp globally if they aren't installed.

### ISSUE THREAD

**Issue by alhalama** [Infragistics/livewire#120]
Yesterday I cloned the repository ad I am on a new machine and I forgot to install bower and gulp before npm install and npm start which resulted in errors trying to use the menus.  It would have been better if when starting livewire I was prompted that bower and gulp needed to be installed to help me catch my mistake.

**Comment by craigshoemaker** [comment]
I cleaned up the `package.json` files to use native `npm` commands instead of Gulp during installation to pull in all dependencies. Closed by cc2d6d13434dea80cd1cb10755fe7950de879198
