### ISSUE TITLE
HTML preview is still displayed after closing 3+ files

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/livewire#41]
1. Open 3 or more files.
2. Close them all.
3. Observer the HTML preview pane.
The HTML preview is still displayed even though no file is open.

**Comment by craigshoemaker** [comment]
I just did it with a number of different files and it works fine for me, but that doesn't mean this area of the code can't be more solid. There is likely an error for some reason happening at another time to trip up the preview pane. 

If you see this again please try to see if there are any other issues happening at the time.

**Comment by ig-ealbert** [comment]
This might only happen if you scroll down in the asciidoc and the preview panes.  Let me know if you'd like me to share my screen so you can watch it happen.
![livewireissue41](https://cloud.githubusercontent.com/assets/8162597/11101938/995d864a-8887-11e5-90ee-af4d9d89d583.png)

**Comment by craigshoemaker** [comment]
I've seen this a few times myself since you mentioned it. I'm not sure on the exact way to replicate yet so if you see anything consistent let me know.

**Comment by ig-ealbert** [comment]
1. Open 3 files.
2. Scroll down a bit in both the source and preview panes.
3. Very quickly, close the files from the tabs, right to left.

**Comment by craigshoemaker** [comment]
closed by 791cdac481c39f24186da6e9d36ac57a477dcd2a
