### ISSUE TITLE
Image handling is not consistent

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/livewire#42]
Sometimes images are shown as broken (expected) and sometimes they are not shown at all.  This should be consistent.
Ex.
shown: datachart-navigating-chart-using-code.ja-JP.adoc
not shown: datachart-creating-custom-series.ja-JP.adoc

**Comment by craigshoemaker** [comment]
Livewire does render them consistently, it's just that all the images in `datachart-creating-custom-series.ja-JP.adoc` are build-flagged so you need to add a build flag at the top to see the images.
