### ISSUE TITLE
no way to click tabs offscreen

### ISSUE THREAD

**Issue by jVanZwieten** [Infragistics/livewire#45]
I was going through test cases using livewire, and wasn't closing tabs as I went.  Since tabs open rightmost, if enough tabs are opened they will eventually start opening to the right of the window and become unclickable.  I wouldn't have thought of this if I hadn't accidentally done it.
![livewire tab bug](https://cloud.githubusercontent.com/assets/16783024/12433504/6f35ba4e-becf-11e5-8577-b9a23c9cbe11.png)

**Comment by craigshoemaker** [comment]
Inside the tab well we need a button with ellipsis that when clicked, exposes a panel with all the open files available to click to.

Here's a mockup:

![image](https://cloud.githubusercontent.com/assets/127797/12465270/0fcf82f2-bf82-11e5-813f-35e8e6671bb2.png)

You can handle the ellipsis button click in the [tabs module](https://github.com/Infragistics/livewire/blob/master/app/modules/toolbars/tabs/index.js). You'll likely want to create a new module to just handle the open files panel. When a user clicks on the name of an open file then you'll want to close the open files panel and call the [switchDocuments](https://github.com/Infragistics/livewire/blob/master/app/modules/toolbars/tabs/index.js#L70) function in the tabs module. The tabs module will take care of most of the work of applying the correct CSS classes and bringing the correct file into the editor.

**Comment by craigshoemaker** [comment]
closed by 99f21d6e882c24e7eb9dc65b6217e939f895815d
