### ISSUE TITLE
File Picker

### ISSUE THREAD

**Issue by craigshoemaker** [Infragistics/livewire#6]
Expose a UI to help you select files when creating a link. 

## User Stories 
1. As a writer when I click on the insert link button I want a window to pop up that allows me to browse the file system for the target file so that I don't have to memorize or manually type file names.

2. As a writer I want (after I select a file) for a link to be made around the selected text that points to the selected file so that I do not have to manually create a link.

3. As a writer I want the resulting link to be rendered in correct format that matches the selected document format (AsciiDoc or Markdown) so that I don't have to format the link manually.

4. As a writer I want the resulting link to format the file name with an `.html` file extension so that the link value reflects what is generated for the website and there will be no broken links.

7. URL format filename

## Comments
The [formats](https://github.com/Infragistics/livewire/tree/master/app/modules/formats) module can help you easily build the link without having to worry about the implementation details of whether the topic is in AsciiDoc or Markdown.

Related to #43

**Comment by kacheshmarova** [comment]
Added with 809c1e1f1e2680aa6d967aab33ab7a622ff278cb

**Comment by craigshoemaker** [comment]
Closed by 6975f6c7d752aa3491116ca0c76a390a80603d51
