### ISSUE TITLE
[iOS Topics] Images Not Properly Formatted

### ISSUE THREAD

**Issue by TorreyBetts** [Infragistics/livewire#65]
The following NucliOS topics contain malformed images.

- igchartview-line-series.adoc
- igchartview-range-column-series.adoc
- igchartview-scatter-series-1.adoc
- igchartview-spline-area-series.adoc
- igchartview-spline-series.adoc
- igchartview-step-area-series.adoc

**Comment by ig-ealbert** [comment]
Fixed in changeset 579166.  The problem was that the text after the image was not in `<P>` tags.  I added the paragraph tags.
