### ISSUE TITLE
Build Flagged Content Showing Up Multiple Times in Preview Pane

### ISSUE THREAD

**Issue by craigshoemaker** [Infragistics/livewire#67]
In some cases build flagged content shows up when it's not supposed to. See this [Convertwire issue for details](https://github.com/Infragistics/convertwire/issues/190).

**Comment by ig-ealbert** [comment]
@craigshoemaker - This seems to be fixed.  I think it was fixed with the introduction of the per-product build flags at the bottom right of Livewire.

**Comment by ig-ealbert** [comment]
I just spoke with Pam and Mike D and they said there's another issue with this, but it's not related to the convertwire issue that you linked above.  It's about when two "multi-product" build flags are used at once.  Pam said that you and Martin already had a solution or something.

**Comment by craigshoemaker** [comment]
The last description is a bit vague, but after some testing it seems any remaining issues were closed by 94ab4f27d6152c1947c71a6ab38e93f9f75897da
