### ISSUE TITLE
List numbering resets

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/livewire#72]
Open wincarousel-binding-data-to-carousel-using-the-designer.adoc.

Observe the steps under "Configure the Data Source".

In English, the numbers reset after each image.
In Japanese, the numbers reset after a step in which there is a space between the list item number and the text of the item.

In English, removing the space fixes the numbering but breaks the indentation.
In Japanese, removing the space fixes the numbering.
In both languages, indenting the image makes it formatted as code (breaks the image).

**Comment by craigshoemaker** [comment]
This isn't a bug in Livewire, but rather just the behavior of AciiDoc. Lists are meant not to have block-level elements (like images) between them, so the `[start=X]` (where X = the number you want the list to be) notation above each list item where you want to continue numbering.

**Comment by ig-ealbert** [comment]
http://tfs.infragistics.local:8080/tfs/Engineering/IgInternalApplicationsGit/_git/winforms-docs-ja/commit/94d2f196f598b0e9f11836d13f97ae6dcc5f0b81
http://tfs.infragistics.local:8080/tfs/Engineering/IgInternalApplicationsGit/_git/winforms-docs-en/commit/d274a88bd5ae09a6200f6249d4fb876c7a7bd833
