### ISSUE TITLE
Link dialog doesn't work

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/livewire#78]
1. Create a new .adoc file.
2. Enter a header and a paragraph.
3. Select a word or phrase in the paragraph and click on the Link icon.
4. Paste in a URL like `http://help.infragistics.com/NetAdvantage/ASPNET/2010.3?page=WebCalcManager_Creating_a_Calculated_Column_in_WebGrid.html`.
5. Click DONE.

Actual Result: Nothing happens and the dialog is not closed.

Expected Result: A link is added with the selected text, and the dialog is closed.

Am I using this functionality wrong?  If I don't select anything, the same problem happens.

**Comment by craigshoemaker** [comment]
closed by ae0232bfaf79b87717abf8686a0d9a179a82fb6c
