### ISSUE TITLE
Displayed file contents are the same when switching between tabs

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/livewire#83]
1. Open an existing .adoc file in Livewire.
2. Create a new file and start writing content.
3. Save it.
4. Switch back and forth between the two tabs.

At some point, the newly saved will have have the same content displayed as the existing file.  The actual file content (if you open it in something like Notepad++) will be correct, but it won't be displayed in Livewire.

**Comment by craigshoemaker** [comment]
related to #81
