### ISSUE TITLE
Unsaved file changes notifications

### ISSUE THREAD

**Issue by craigshoemaker** [Infragistics/livewire#9]
Alert user when they are closing a tab or closing the program when a file has unsaved changes
## User Stories
1. As a writer I want to be notified if I try to close a tab with unsaved changes so that I don't accidentally lose edits I have made to the topic
2. As a writer I want to be notified if I try to close the application with unsaved changes so that I don't accidentally lose edits I have made to the topic
3. As writer I want to be presented with a single list of all documents that have unsaved changes if I try to close the application before saving changes so that I don't have a series of modals that I have to click away (for each topic with unsaved data).
## Comments

Depends on #10

**Comment by craigshoemaker** [comment]
This issue is dependent on the foundation being built underneath #10

**Comment by ig-ealbert** [comment]
Three issues found during testing.
1. Open an existing file.  Write new content.  Try to close the tab (select no).  Save the file with the icon on the toolbar.  *Result*: The \* doesn't go away in the tab.
2. Open an existing file.  Edit both the content and the metadata.  *Result*: Two \*s appear in the tab.
3. Create a new file.  Make some edits.  Save.  Make some edits.  Close without saving.  *Result*: The window name appears as that topic title.
