### ISSUE TITLE
Clicking on a link inside Livewire breaks the application

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/livewire#91]
1. Open a file with a link like web-whats-new-in-2013-volume-1.adoc.
2. Click on a link to another topic (did this accidentally).

The Livewire application no longer displays the toolbar, the file, or the preview.

Unable to open the dev tools.

**Comment by craigshoemaker** [comment]
duplicate of #63

**Comment by craigshoemaker** [comment]
Clicking on the same link multiple times seems to eventually expose the error.
