### ISSUE TITLE
Newer versions of node break livewire

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/livewire#94]
In the X# team training, anyone who installed node 6.5 can't open any files in Livewire.  Even after going back to 4.5 (recommended version).  Ask Nelly for more information.
I had this problem before and had to reinstall everything or use the installer.

**Comment by ambroselittle** [comment]
I assume this is the issue that produces a blank screen when opening MD files as I am seeing? Any ideas on fixing?

**Comment by ig-ealbert** [comment]
Yes it does.  There are 2 workarounds:

1. Use the installer.
2. Delete the repository completely from your local machine and redo all of the steps, making sure to use the 4.5.0 (LTS) version of Node.  Not even sure if this will work.  It worked for me but I don't think I ever had a new version of Node installed.

No idea what the "fix" is.  Craig mentioned updating electron, but this would be a major change to the application so I don't expect it to be quick.

**Comment by ambroselittle** [comment]
Yeah, I'm on Mac, and we don't have an installer for Mac yet. :) 

Thanks, I may try the other approach. @craigshoemaker, you should fix this! :-p

**Comment by craigshoemaker** [comment]
@ambroselittle - working on it ;)

**Comment by craigshoemaker** [comment]
Closed by 747c4db8f980dffaea2891a2641175364d8133d7. Hoping this helps a bit, @ambroselittle ;)
