### ISSUE TITLE
Keywords are not displayed within a table

### ISSUE THREAD

**Issue by pamelabrasil** [Infragistics/livewire#98]
When there are any code snippets, bullets, or headers placed within a table cell, they will not render in the expected format, only as plain text.

**Comment by jVanZwieten** [comment]
I'm showing UL, LI, header, and snippet rendering in the table cell. I'm using 1.1.0 may be an issue in the latest. Ensure that there's a white space before the special line.

**Comment by craigshoemaker** [comment]
Turns out this is a syntactical issue, not a bug in Livewire. If you can format columns as AsciiDoc via the `cols` attribute: 
```
[options="header", cols="20a,80a", width="75%"]
|====
|Topic|Purpose
```
Here are docs on the particulars of tables:
 - http://www.methods.co.nz/asciidoc/chunked/ch23.html
 - http://www.methods.co.nz/asciidoc/newtables.html
