### ISSUE TITLE
Critical - Add button for synchronizing DocsConfig.xml file

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [Infragistics/livewire#99]
- Add option to pull DocsConfig.xml file from a directory (local TFS location)
- Add button for synchronizing DocsConfig.xml file
- Add option to detect changes to DocsConfig.xml files and load them from TFS location:
$/NetAdvantage/DEV/XPlatform/2017.1/PG

**Comment by craigshoemaker** [comment]
closed by 32570536bfb92b655b1ee69cde9249d5732d0dca

There is no feature to automatically detect changes, but if you load a new version of an existing DocsConfig.xml, Livewire will overwrite the current one it is using.
